function proiect(R,L,C,selectare_grafic)
 
 
% main window    
figure('Name','WOOF',...
        'Numbertitle','off',...
        'Units','normalized',...
        'Position',[0.1 0.05 0.8 0.87],...
        'Color','w',...
        'DefaultAxesColor',[1.0 0.95 0.9]);
 l=axes('units','normalized',...
    'position',[0 0 1 1]);
uistack(l,'bottom');
I=imread('poze/paw2.png');
q=imagesc(I);
set(gca,'Position',[0 0 1 1]);
set(q,'alphadata',.95);
colormap gray
set(l,'handlevisibility','off',...
    'visible','off');       
    % menu       
          f=uimenu('Label','Documentation',...
         'foregroundcolor','#Ff00c5');
uimenu(f,'Label', 'Documentation',...
    'Callback','open(''Documentatie.pdf'')');
uimenu(f,'Label','Bibliography',...
    'Callback','open(''Bibliografie.pdf'')');
uimenu(f,'Label','Close',...
    'Callback','close',...
    'Separator','on','Accelerator','Q');

% data
        param=uibuttongroup('Visible','on',...
                      'BackgroundColor','#8ef9da',...
                      'ForegroundColor','#2b3e28',...
                      'FontSize',12,...
                      'FontWeight','b',...
                      'TitlePosition','centertop',...
                      'Title','Initial parameters',...
                      'Position',[0.57 0.77 0.20 0.20]);
                  
          % resistance
                    uicontrol('Style','Text',...
                              'Units','Normalized',...
                              'Position',[0.1 0.65 0.35 0.15],...
                              'BackgroundColor','#8ef9da',...
                              'ForegroundColor','#000000',...
                              'FontSize',11,...
                              'FontWeight','b',...
                              'String',' R [Ohm]',...
                              'Parent',param);
                    uicontrol('Style','Edit',...
                              'Units','Normalized',...
                              'Position',[0.56 0.65 0.35 0.2],...
                              'BackgroundColor','#5ea490',...
                              'ForegroundColor','w',...
                              'FontSize',11,...
                              'String',R,...
                              'Callback','R=str2num(get(gco,''String''));close;proiect(R,L,C,selectare_grafic)',...
                              'Parent',param);
            % coil
                    uicontrol('Style','Text',...
                              'Units','Normalized',...
                              'Position',[0.1 0.43 0.35 0.15],...
                              'FontSize',11,...
                              'BackgroundColor','#8ef9da',...
                              'ForegroundColor','#000000',...
                              'FontWeight','b',...
                              'String',' L[ H ]',...
                              'Parent',param);
                     uicontrol('Style','Edit',...
                              'Units','Normalized',...
                              'Position',[0.56 0.43 0.35 0.2],...
                              'BackgroundColor','#5ea490',...
                              'ForegroundColor','w',...
                              'FontSize',11,...
                              'String',L,...
                              'Callback','L=str2num(get(gco,''String''));close;proiect(R,L,C,selectare_grafic)',...
                              'Parent',param);
            % cap
                     uicontrol('Style','Text',...
                               'Units','Normalized',...
                               'Position',[0.1 0.21 0.35 0.15],...
                               'BackgroundColor','#8ef9da',...
                               'ForegroundColor','#000000',...
                               'FontSize',11,...
                               'FontWeight','b',...
                               'String',' C[ F ]',...
                               'Parent',param);
                     uicontrol('Style','Edit',...
                               'Units','Normalized',...
                               'Position',[0.56 0.21 0.35 0.2],...
                               'BackgroundColor','#5ea490',...
                               'ForegroundColor','w',...
                               'FontSize',11,...
                               'String',C,...
                               'Callback','C=str2num(get(gco,''String''));close;proiect(R,L,C,selectare_grafic)',...
                               'Parent',param);
                           
                           
% calcul
             uibuttongroup('Visible','on',...
                          'BackgroundColor','#8ef9da',...
                          'ForegroundColor','#2b3e28',...
                          'FontSize',12,...
                          'FontWeight','b',...
                          'TitlePosition','centertop',...
                          'Title','Calculated',...
                          'Position',[0.79 0.77 0.20 0.2]); 
             
           uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'BackgroundColor','#5ea490',...
          'ForegroundColor','w',...
          'FontWeight','bold',...
          'Position',[0.005 0.005 0.04 0.032],...
          'String','BACK',...
          'FontSize',12,...
          'Callback','start()');


           uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'BackgroundColor','#5ea490',...
          'ForegroundColor','w',...
          'FontWeight','bold',...
          'Position',[0.955 0.005 0.04 0.032],...
          'String','CLOSE',...
          'FontSize',12,...
          'Callback','close');
  
% dropdown
      uicontrol('Style','Text',...
                'Units','Normalized',...
                'Position',[0.6 0.73 0.18 0.025],...
                'FontSize',15,...
                'BackgroundColor','#8ef9da',...
                'ForegroundColor','r',...
                'FontWeight','b',...
                'String','Select graph from menu:');
     uicontrol('Style','PopupMenu',...
               'BackgroundColor','#5ea490',...
               'ForegroundColor','w',...
               'Units','normalized',...
               'Position',[0.78 0.73 0.15 0.03],...
               'value',selectare_grafic,...
               'String','GAIN|(U2/U1)|PHASE|ALL|IMPEDANCE',...
               'FontSize',13,...
               'Callback','selectare_grafic=get(gco,''value'');close;proiect(R,L,C,selectare_grafic)');  	                       
         
				  im=imread('poze/ftb.png');
				  image(im);
				  axis off; 
                  set(gca,'Position',[0.012 0.74 0.51 0.25]);
                          
% graf

switch(selectare_grafic)
	case 1     
         % calcule
                        Q=sqrt(L/C)./R;         %factorul de calitate
                        f0=1/(2*pi*sqrt(L*C));  %frecventa de taiere
                        x=logspace(-1,1,300);
                        f=x.*f0;
                        w=2.*pi.*f;
                  
						numarator=R; 
						numitor=R+1i.*w.*L+1./(1i.*w.*C);
						fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
						fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
						BandaFrecv=fmax-fmin;
						faza1=45;
						faza2=-45;
             % formule					
                            %Uies/Uin
                         h=abs(numarator./numitor);
                            %calcul gain
                         gain=20*log10(h);
                            %frecventa 
                         f=w/(2*pi);
                            %faza
                          Faza=angle(numarator./numitor)*180./pi;   
                          
            % gain
            subplot('Position', [0.06 0.30 0.85 0.25]);    
                  semilogx(f,gain,'b',fmin,-3,'b*',fmax,-3,'k*',f0,0,'r*','MarkerSize',12,'MarkerFaceColor',[0.5,0.5,0.5],'LineWidth',2);              
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('Gain(dB)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('Gain','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('Gain','fmin','fmax','f0'); 

                     
   case 2 
    % calcule
                        Q=sqrt(L/C)./R;         %factorul de calitate
                        f0=1/(2*pi*sqrt(L*C));  %frecventa de taiere
                        x=logspace(-1,1,300);
                        f=x.*f0;
                        w=2.*pi.*f;
                       
						numarator=R; 
						numitor=R+1i.*w.*L+1./(1i.*w.*C);
						fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
						fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
						BandaFrecv=fmax-fmin;
						faza1=45;
						faza2=-45;
             % formule					
                            %Uout/Uin
                         h=abs(numarator./numitor);
                            %gain
                         gain=20*log10(h);
                            %frecventa
                         f=w/(2*pi);
                            %faza
                          Faza=angle(numarator./numitor)*180./pi;   
         % U2/U1
                      subplot('Position',  [0.06 0.30 0.85 0.25]);
                       semilogx(f,h,'r','LineWidth',2);
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('(U2/U1)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('U2/U1','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('U2/U1'); 
                    
    case 3
              % calcule
                        Q=sqrt(L/C)./R;         %factorul de calitate
                        f0=1/(2*pi*sqrt(L*C));  %frecventa de taiere
                        x=logspace(-1,1,300);
                        f=x.*f0;
                        w=2.*pi.*f;
                   
						numarator=R; 
						numitor=R+1i.*w.*L+1./(1i.*w.*C);
						fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
						fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
						BandaFrecv=fmax-fmin;
						faza1=45;
						faza2=-45;
             % formule					
                            %Uout/Uin
                         h=abs(numarator./numitor);
                            %gain
                         gain=20*log10(h);
                            %frecventa
                         f=w/(2*pi);
                            %faza
                          Faza=angle(numarator./numitor)*180./pi;             
            % faza
                       subplot('Position',   [0.06 0.30 0.85 0.25]);
                       semilogx(f,Faza,'k','LineWidth',2);
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('Phase(degrees)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('Signal Phase','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('Phase');  
                     
    case 4
        % calcule
                        Q=sqrt(L/C)./R;         %factorul de calitate
                        f0=1/(2*pi*sqrt(L*C));  %frecventa de taiere
                        x=logspace(-1,1,300);
                        f=x.*f0;
                        w=2.*pi.*f;
                    
						numarator=R; 
						numitor=R+1i.*w.*L+1./(1i.*w.*C);
						fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
						fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
						BandaFrecv=fmax-fmin;
						faza1=45;
						faza2=-45;
             % formule					
                            %Uout/Uin
                         h=abs(numarator./numitor);
                            %gain
                         gain=20*log10(h);
                            %cfrecventa in functie de w
                         f=w/(2*pi);
                            %faza
                          Faza=angle(numarator./numitor)*180./pi; 
           % gain
                    subplot('Position', [0.06 0.53 0.9 0.15]);    
                       semilogx(f,gain,'b',fmin,-3,'b*',fmax,-3,'k*',f0,0,'r*','MarkerSize',12,'MarkerFaceColor',[0.5,0.5,0.5],'LineWidth',2);              
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('Gain(dB)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('Gain','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('Gain','fmin','fmax','f0'); 
          % U2/U1
                    subplot('Position',  [0.06 0.06 0.9 0.15]);
                       semilogx(f,h,'r','LineWidth',2);
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('(U2/U1)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('U2/U1','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('U2/U1'); 
           % faza
                    subplot('Position',   [0.06 0.30 0.9 0.15]);
                       semilogx(f,Faza,'k','LineWidth',2);
                       grid on;
                       xlabel('Frequency(Hz)','Color','w','FontWeight','b', 'BackgroundColor','#5ea490');
                       ylabel('Phase(degrees)','Color','w','FontWeight','b', 'BackgroundColor','#5ea490');
                       title('Signal Phase','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('Phase');
    case 5
                        % calcule
                        Q=sqrt(L/C)./R;         %factorul de calitate
                        f0=1/(2*pi*sqrt(L*C));  %frecventa de taiere
                        x=logspace(-1,1,300);
                        f=x.*f0;
                        w=2.*pi.*f;
 
						numarator=R; 
						numitor=R+1i.*w.*L+1./(1i.*w.*C);
						fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
						fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
						BandaFrecv=fmax-fmin;
						faza1=45;
						faza2=-45;
             % formule		
 			            zz = R + 1./(j.*w.*C) + (j.*w.*L);
                        z = abs(zz);
                        f=w/(2*pi);
           
            % impedance
                       subplot('Position',   [0.06 0.30 0.85 0.25]);
                       semilogx(f,z,'g','LineWidth',2);
                       grid on;
                       xlabel('Frequency(Hz)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       ylabel('Impedance(Ohm)','Color','w', 'BackgroundColor','#5ea490','FontWeight','b');
                       title('IMPEDANCE','Fontweight','b','FontSize',13,'Color','w', 'BackgroundColor','#5ea490');
                       legend('Impedance');
                     
end
   % properties 
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.82,0.9,0.12,0.025],...
                      'BackgroundColor','#8ef9da',...
                      'ForegroundColor','k',...
                      'FontSize',13,...
                      'FontWeight','b',...
                      'String',['Q = ',num2str(Q)]); 
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.823,0.87,0.12,0.025],...
                      'BackgroundColor','#8ef9da',...
                      'ForegroundColor','k',...
                      'FontSize',13,...
                      'FontWeight','b',...
                      'String',['F max = ',num2str(fix(fmax)),' Hz ']); 
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.82,0.84,0.12,0.025],...
                      'BackgroundColor','#8ef9da',...
                      'ForegroundColor','k',...
                      'FontSize',13,...
                      'FontWeight','b',...
                      'String',['F min = ',num2str(fix(fmin)),' Hz ']); 
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.823,0.81,0.12,0.025],...
                      'BackgroundColor','#8ef9da',...
                      'ForegroundColor','k',...
                      'FontSize',13,...
                      'FontWeight','b',...
                      'String',['F Band = ',num2str(fix(BandaFrecv)),' Hz ']);            
                    
end