% Ples Andrei-Valentin
% Gr 2022
% Band pass filter
clear all 
close all
clc

Fig=figure('Name',':D',...
'Units','normalized',...
'Position',[0.05 0.03 0.9 0.9],...
'NumberTitle','off',...
'color',[0.05 0.2 0.3]);

l=axes('units','normalized',...
    'position',[0 0 1 1]);
uistack(l,'bottom');
I=imread('poze/img2.jpg');
q=imagesc(I);
set(gca,'Position',[0 0 1 1]);
set(q,'alphadata',.95);
colormap gray
set(l,'handlevisibility','off',...
    'visible','off');

% initiere date % 

    R=40;
    L=1;
    C=0.001;
    
selectare_grafic=4;

Bp=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.35 0.45 0.3 0.2],...
'Fontsize',40,...
'Fontweight', 'b',...
'String','Band PASS Filter',...
'Callback','close;proiect(R,L,C,selectare_grafic)',...
'backgroundcolor','#580047',...
'foregroundcolor','#fec4e7',...
'Visible','on');

url = 'https://www.omfgdogs.com/#';

Bt=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.35 0.8 0.3 0.06],...
'Fontsize',20,...
'backgroundcolor','#580047',...
'foregroundcolor','#fec4e7',...
'Callback', 'web(url)',... 
'String','Computer Aided Graphics');

url2 = 'https://openpuppies.com/#Dp9iPV8';

Bt=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.65 0.1 0.3 0.08],...
'Fontsize',20,...
'backgroundcolor','#580047',...
'foregroundcolor','#fec4e7',...
'Callback', 'web(url2)',... 
'String', 'Ples Andrei-Valentin');



